### ISSUE TITLE
Command failed with exit code 1: git checkout refs/pull/3/merge

### ISSUE THREAD

**Issue by Lenny4** [salsify/action-detect-and-tag-new-version#31]
Here is my `.github/workflows/ci.yml`:

```yaml
name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  linux-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # https://github.com/marketplace/actions/detect-and-tag-new-version#usage
      - uses: salsify/action-detect-and-tag-new-version@v2 # https://github.com/marketplace/actions/detect-and-tag-new-version#usage
        with:
          version-command: |
            yq '.version' pubspec.yaml
```
When I run it in github I got error `Error: Command failed with exit code 1: git checkout refs/pull/3/merge`

![image](https://github.com/salsify/action-detect-and-tag-new-version/assets/25544892/6cdb0312-3554-4b7d-a994-58063eeeb36f)

What am I missing here ?

In `pubspec.yaml` I got:

```yaml
# ...
version: 0.0.1+3
# ...
```
