### ISSUE TITLE
File not found /dist/index.js

### ISSUE THREAD

**Issue by FlowMatric** [salsify/action-detect-and-tag-new-version#35]
I am using the action in conjunction with poetry like so:

```yaml
      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@624bb847c54529c8c4175cb36b534b101daae484
        with:
          version-command: |
            bash -o pipefail -c "poetry version | awk '{ print \$2 }'"
```

I doubt that it has to do with the _version-command_ as the error message is:

`File not found: '/home/runner/work/_actions/salsify/action-detect-and-tag-new-version/624bb847c54529c8c4175cb36b534b101daae484/dist/index.js'`

**Comment by DeanLa** [comment]
This commit doesn't have `index.js`
Try
```yaml
      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            bash -o pipefail -c "poetry version | awk '{ print \$2 }'"
```
